### ISSUE TITLE
How to change installer icon?

### ISSUE THREAD

**Issue by NxRoot** [rabbit-hole-syndrome/electron-forge-maker-portable#1]
Ive tried to add the icon via config but no luck...
The excutable appears like setup icon on the desktop, but when i open the executable properties the icon is there.
```
"icon": "/icon.png",
"portable": {
  "artifactName": "${productName}.exe"
}
```
Any idea on how to replace the installer icon?

**Comment by gregnr** [comment]
Hi @NxRoot, sorry to hear you're having issues with the icon. Since this Maker uses `electron-builder` under the hood, I took a quick look through their GH issues to see if there's anything related. I found this issue that may be related:

https://github.com/electron-userland/electron-builder/issues/4241

Would you mind following the comments in that thread and confirm whether or not your situation is similar to theirs?

**Comment by NxRoot** [comment]
Hi @gregnr it doesn't seem to be the same issue. When using resource hacker I was able to verify that the icon is packed inside the installer executable, but for some reason sometimes windows seems to detect the executable as an extractor or something, and sets the icon to the setup icon. It doesn't seem to be anything related from your side, appears to be only a windows problem. Thanks for your help, I will close this issue.
